# Generated by Django 4.2.2 on 2024-01-11 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('sessionID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('isActive', models.BooleanField()),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('msgID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=1000)),
                ('senderID', models.BigIntegerField(unique=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('mark', models.BooleanField()),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.chatsession')),
            ],
        ),
    ]
