# Generated by Django 4.2.2 on 2024-01-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_chatsession_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='sessionID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
