# Generated by Django 4.2.2 on 2024-01-12 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_chatsession_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
